name: Check Article Status

on:
  schedule:
    - cron: '0 8 * * *'  # Exécution tous les jours à 8h00
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  check-status:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps chromium
        
    - name: Run status check
      env:
        USERNAME: ${{ secrets.EM_USERNAME }}
        PASSWORD: ${{ secrets.EM_PASSWORD }}
      run: npx playwright test
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add status.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update article status" && git push) 