name: Check Article Status

on:
  schedule:
    - cron: '0 8 * * *'  # Exécution tous les jours à 8h00
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  check-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps firefox
        
    - name: Run status check
      env:
        EM_USERNAME: ${{ secrets.EM_USERNAME }}
        EM_PASSWORD: ${{ secrets.EM_PASSWORD }}
      run: npx playwright test --project=firefox
      
    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add status.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update article status" && git push origin HEAD:main) 